server:
  port: 9091

spring:
  rabbitmq:
#    host: ec2-3-35-229-119.ap-northeast-2.compute.amazonaws.co
    addresses: amqps://b-f96775a8-8bcb-4e8f-a88d-f5e27cb54f03.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!