server:
  port: 9090
<<<<<<< HEAD
spring:
  rabbitmq:
    addresses: amqps://b-76783b42-45e7-4b95-b86c-a27a43b9787a.mq.ap-northeast-2.amazonaws.com:5671
    username: rabbitmq
    password: password123!
=======

spring:
  rabbitmq:
    host: ec2-3-35-229-119.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
>>>>>>> 964e2b4f224d5cfb112bc7a3f1938e85031788fa
